### PR TITLE
Added support for using TTL

### PR DESCRIPTION
**Pull request by panki3a**
Added support for using TTL in Insert command into Cassandra.

### CODE REVIEW

**Comment by Hendra-Huang** [comment]
Did you mean to set a ttl for a table ? If you mean to set ttl for a table, I think its better to set the default_time_to_live while creating the table. But if you mean to set ttl for each insert, I think its better to add additional $options argument on insert method to specify the ttl.

What do you think about it ?

**Comment by panki3a** [comment]
Yes, you have right. It will by better to implemet option for each insert,update command. I will look at it and then i will send pull request

**Comment by Hendra-Huang** [comment]
Okay. Thanks.

**Comment by panki3a** [comment]
I implemented class Options and i used it as optional parameter in insert and update method in EntityManager.
I changed ttl anotation to defaultTtl, and i add ifNoExist annotations.

**Comment by Hendra-Huang** [comment]
Thanks @panki3a

**Comment by panki3a** [comment]
will you create a tag version in near future ?

**Comment by Hendra-Huang** [comment]
Yes there are tags now

**Comment by panki3a** [comment]
thanks @Hendra-Huang

**Pull request merged**
